### ISSUE TITLE
Polymart Marketplace

### ISSUE THREAD

**Issue by devbaraus** [aematsubara/RealisticVillagers#11]
Could you add the plugin to polymart?

**Comment by aematsubara** [comment]
Hi! while it would be great to add other payment methods (something that polymart offers), currently stripe doesn't work in my country (Argentina), so for the moment it would be unnecessary as the plugin could only be purchased by paypal (which you can already do in spigot).

Unless I am missing other benefits that polymart offers that I don't know about? (Sorry, I've never used polymart)

Best regards!
