### ISSUE TITLE
give npc gift problem

### ISSUE THREAD

**Issue by Xzavier0707** [aematsubara/RealisticVillagers#14]
similar to this issue https://github.com/aematsubara/RealisticVillagers/issues/4
When I give gifts to npc they don't pick it up and walk away, when I pick it up they come back instead (only some npcs are like this)
 I use the paper-1.19.2-237 core

**Comment by aematsubara** [comment]
Hi! Any more details that you can give about those villagers? there must be a pattern for those villagers who pick gifts and the ones who can't; for example, maybe those who walk away are doing other stuff?

**Comment by aematsubara** [comment]
Oh ok, I'll try not checking if the event of villager picking an item is cancelled, probably that would work;

**Comment by aematsubara** [comment]
> Oh ok, I'll try not checking if the event of villager picking an item is cancelled, probably that would work;

Done, please, let me know if this still happening!

**Comment by Xzavier0707** [comment]
Still having issues, but I've found a pattern, it's when they're holding the fishing rod

**Comment by aematsubara** [comment]
I think I found the issue; another question, do this happen when the activity of villagers is MEET? at least this error happens when they're in MEET activity (when they go to the bell and gossip)

**Comment by Xzavier0707** [comment]
I'm sorry, but I kind of don't understand what this means？

**Comment by aematsubara** [comment]
Don't worry, I think I finally found the solution

**Comment by Xzavier0707** [comment]
So far it's working normally

**Comment by aematsubara** [comment]
Hi! is this still happening or can I close this issue?

**Comment by Xzavier0707** [comment]
No,this issue is solved perfectly,I'm sorry I usually don't pay attention to the mailbox, I just found out now



At 2022-11-15 00:01:14, "Agustín Matsubara" ***@***.***> wrote:

Hi! is this still happening or can I close this issue?
