### ISSUE TITLE
NPC trade 

### ISSUE THREAD

**Issue by Xzavier0707** [aematsubara/RealisticVillagers#15]
When NPCs have a profession, their trades still don't work
https://prnt.sc/z0Mw3wsdi-Dz
https://prnt.sc/rVGYFgTm__4P

**Comment by aematsubara** [comment]
Were you trading with that villager before? It's possible that the villager has run out of stock (vanilla thing)

**Comment by Xzavier0707** [comment]
No,I didnt trade before

**Comment by Xzavier0707** [comment]
The problem was solved when I restarted the server
