### ISSUE TITLE
FEATURE REQUEST: Heavily armored villagers

### ISSUE THREAD

**Issue by marcelschoen** [aematsubara/RealisticVillagers#16]
I am running a hardcore survival server (inspired by RL Craft), with several plugins that make mobs a lot harder and more dangerous (including some randomly spawning mini-bosses etc.). That makes life also more difficult for the villagers. While I can increase their max health (which I did), it would be nice to have one of several config switches to enforce that all the villagers are armored and armed.

Maybe allow to add a list of armor parts and weapons (like a loot table) of which the plugin will assign armor to each generated villager randomly.

Also, while it's a rare thing, sometimes villages are generated near a pillager tower. It would be cool if the villagers were especially heavily armed in such a scenario (i.e. a pillager tower being less than 200 blocks away or so).

**Comment by aematsubara** [comment]
Hi! This sounds like a good suggestion; I'll keep it in mind for a future update!

**Comment by aematsubara** [comment]
Take a look at the new spawn-loot system; sorry for the long wait!
