### ISSUE TITLE
villager create big tps drop

### ISSUE THREAD

**Issue by XionioXMaster** [aematsubara/RealisticVillagers#18]
![image](https://user-images.githubusercontent.com/86433158/202913382-854152af-34ff-4ced-9676-4ae3967c1647.png)

**Comment by XionioXMaster** [comment]
![image](https://user-images.githubusercontent.com/86433158/202914577-a311a238-38bc-4e89-a061-0cf644d3968d.png)

**Comment by aematsubara** [comment]
Thanks for letting me know, I'll take a look at it!

**Comment by aematsubara** [comment]
A lot of improvements since this has been created; please, if you still got more TPS errors reopen or create a new issue!
