### ISSUE TITLE
Issue getting the plugin started

### ISSUE THREAD

**Issue by pajamaben** [aematsubara/RealisticVillagers#2]
Hello! I can't seem to get the plugin to work properly, I'm using the latest version of Paper 1.19.2 and the latest protocolLib dev build and I've even removed all other plugins to make sure nothing was interfering, and I've restarted several times. Not sure what I'm doing wrong

**Comment by aematsubara** [comment]
Hi! What isn't working exactly? Is the plugin in green when doing /plugins? If so, check the config, in the world filter section to select in which worlds villagers should be replaced. If you want this to work in every worlds, set the filter type to BLACKLIST and left the list either empty or with a random world name

**Comment by pajamaben** [comment]
Thanks! I did miss the whitelist section, but I do have a different problem now that they're working (sorry if this is another obvious one) the line under a villagers shows some odd text 
![2022-09-26_14 06 07](https://user-images.githubusercontent.com/10007990/192350113-f6931909-a445-46c0-bd80-1590e58f4cba.png)
But when further away the name shows fine, the plugin shows as green under /plugins (and did before) i tried regenerating the plugin ymls but that didnt seem to do anything
![2022-09-26_14 06 41](https://user-images.githubusercontent.com/10007990/192350128-c6e3bb15-ec2d-427d-9336-8d5563a9110c.png)
Sorry again for the hassle and thank you

**Comment by aematsubara** [comment]
No problem!

Are you using any plugins that may be adding that extra line to the name? Because this plugin doesn't do that

**Comment by pajamaben** [comment]
I only have realisticvillagers and the latest protocollib. I created a new folder and got the latest paper and started anew and that fixed it for a bit, but I opened it today and the problem was back. Ill try it again after I'm off work but I have no idea what I could be doing to cause it to come back

**Comment by pajamaben** [comment]
please ignore that, I was running the wrong one. As far as ive seen, making a completely new 1.19.2 world fixed that issue

**Comment by aematsubara** [comment]
No problem! Good to know it's working. If you got more problems, create another issue.
