### ISSUE TITLE
what???

### ISSUE THREAD

**Issue by Decakeee** [aematsubara/RealisticVillagers#21]
how to delete this...
![p6YNl0OPGXy0qXej8glEscDOI17NmLOV2PUc-ykY-2V3v2XpgfI73T3Rx0DvVOmlg8NDUksuwiyAoYFQ0ruoEsh_](https://user-images.githubusercontent.com/105897305/216263983-ace74bf9-84dc-4e0c-82f7-a2ef44fac992.jpg)

**Comment by aematsubara** [comment]
I downloaded all the skins from the original MCA plugin, I can swear I didn't know that skin was part of them. However, that skin doesn't look like the one from the pack, could you place any type of villager job block like a composter or something like that near to the villager, to see if the skin changes too?

**Comment by Decakeee** [comment]
> 

Ok, i will try. In any case, no big deal. I think it might be someone's prank

**Comment by aematsubara** [comment]
So, I took a look at all the male skins but I couldn't found that skin... is probably the server running offline? sometimes, NPC's takes a random skin (no idea why) when running without internet connection or in offline mode. I can probably create a debug stick to see internal information of the NPC, however, this is really weird

**Comment by aematsubara** [comment]
I'll guess this is solved? Create a new issue otherwise
