### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by CaptainSnickerz** [aematsubara/RealisticVillagers#22]
hey not sure what im doing haha
pls let me know if this isnt in the right area!

having a compatibility issue with the magic plugin
is there anyone that can help me fix it please?

this is the error my console is producing:
https://pastebin.com/einXu7w8

using magic 10.8.7 (latest available) and realisticvillagers 2.0.2 (latest available) on paper 1.18.2

**Comment by CaptainSnickerz** [comment]
really could do with some help with this if at all possible :):)

**Comment by CaptainSnickerz** [comment]
dying to test your plugin

**Comment by CaptainSnickerz** [comment]
https://www.spigotmc.org/resources/magic.1056/

**Comment by CaptainSnickerz** [comment]
i asked magic developer an they said:
"It seems like they are creating custom entities that have a null name, which breaks the Bukkit API.

I'm just calling Entity.getCustomName(), which shouldn't throw an exception."

i then asked if there was anything they could do to fix the error and they said:
"Not really - it'd be one thing if that method was returning null, I could check for it- but that method is actually throwing an error from inside internal CraftBukkit code, because that code does not expect the entity name to be null."

**Comment by CaptainSnickerz** [comment]
hope that helps :D

**Comment by aematsubara** [comment]
I think I found a solution for this issue, I'll give you a test release in discord!

**Comment by CaptainSnickerz** [comment]
thank you that would be amazing

**Comment by CaptainSnickerz** [comment]
https://pastebin.com/TRVhLrwH
next errors it produces

**Comment by aematsubara** [comment]
All fixed in discord!
