### ISSUE TITLE
Feature Request: Death Messages.

### ISSUE THREAD

**Issue by ItzASecret** [aematsubara/RealisticVillagers#26]
Villagers shouldn't say anything when hit if the final hit given was a fatal blow. Meaning, when killed villagers shouldn't speak. As it is now villagers will still speak their hurt message when dead, 

If we are gonna have them talk upon death, it would be cool to set configurable final death messages that are separate from the ones that play when damaged.

**Comment by aematsubara** [comment]
FIxed in the latest commit, I'll update soon! thanks for reporting
