### ISSUE TITLE
It can not be translated?

### ISSUE THREAD

**Issue by 982074664** [aematsubara/RealisticVillagers#30]
![image](https://github.com/aematsubara/RealisticVillagers/assets/104291510/b553c06d-0176-4b58-8d55-bf3b59cf0bf6)
![image](https://github.com/aematsubara/RealisticVillagers/assets/104291510/cdf6974c-7691-492d-93b1-a1f3028eb92c)
The plugin always warning it's wrong . How to translate it as a decent format?
Can you give a sample? Thank you.

**Comment by aematsubara** [comment]
Hey! Do you got any error in console?

**Comment by aematsubara** [comment]
Make sure that you have the flag `-Dfile.encoding=UTF-8` in your start.bat file; if this doesn't work, create another issue!
