### ISSUE TITLE
SUGGESTION + Question: Leather Color

### ISSUE THREAD

**Issue by MarkinhosMLP** [aematsubara/RealisticVillagers#31]
how can i define the leather-color?? i tried with hex and rgb but couldnt figure it out
but also heres a suggestion: allowed color list

```
leather-color:
- '#00000'
- '#00CAFF'
- '#EE00FF'
```

**Comment by aematsubara** [comment]
Hi! Sorry for the late response,

Right now, to set the color of a leather armor piece you need to set the `leather-color` to a color from [Color](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Color.html) or you can set it to `$RANDOM` to use a random color.

Your suggestions for the allowed color list, is to get a random color from that list?

**Comment by aematsubara** [comment]
Added in latest release!
