### ISSUE TITLE
Faraway Chunks (30m+ blocks) load realvillager entities after plugin delete.

### ISSUE THREAD

**Issue by ezriharmusial** [aematsubara/RealisticVillagers#36]
Okey, this is a complicated one.

I have far away chunks loading in on my server that contain Realisitic Villager entity info. The problem is not the villagers. I dont care about that. But the fact that my server keeps loading these chunks Messing up all my other plugins i want to use besides RV.

At the moment, all my plugins are disabled. Command blocks are disabled and all but my Terralith and Cavernous datapack are enabled. Because without them my server breaks.

I am not saying your Plugin is the cause, as it is turned off. But the Faraway chunks generate info that remind me of your plugin. 

Is there any other place besides the world/poi, world/entities or world/regions folder, references to either Entities or the Region is stored?

Hope you can help me clear this persistent yet illussive problem.

**Comment by aematsubara** [comment]
Could you please explain it better? I don't understand what the real problem is. Server crashes? Any error in console?
