### ISSUE TITLE
Giving a gift problem

### ISSUE THREAD

**Issue by InternetVet** [aematsubara/RealisticVillagers#4]
step 1: find villager

step 2: try to give them cake

step 3: they just stand there looking at it 

step 4: you pick it up and they say a response about how they thought you were going to give them a gift.

https://prnt.sc/3mlQ04xbN-9C

**Comment by aematsubara** [comment]
Which server version are you using? Also, do that happen in every place or only in snow like the image?

**Comment by InternetVet** [comment]
Im using paper 1.19.2, newest paper release #177, happens all the time from what i can tell

**Comment by InternetVet** [comment]
might be faster to message on dc, internetvet#7876

**Comment by aematsubara** [comment]
> might be faster to message on dc, internetvet#7876

Agree, but that discord isn't working

**Comment by InternetVet** [comment]
𝐼𝓃𝓉𝑒𝓇𝓃𝑒𝓉𝒱𝑒𝓉#7876

try that
