### ISSUE TITLE
Villagers become witches. Names don't disappear.

### ISSUE THREAD

**Issue by HYDeath** [aematsubara/RealisticVillagers#40]
The plugin was tested using the latest version, and after the villager turns into a witch, the head tag throw is still there and won't disappear.

![image](https://github.com/aematsubara/RealisticVillagers/assets/65531310/5de8d27e-ecbe-4277-b81d-12c0786d61f4)

![image](https://github.com/aematsubara/RealisticVillagers/assets/65531310/6f9b2202-b98a-4299-a946-1e7e4faaf1f5)

**Comment by aematsubara** [comment]
Fixed on the latest release!
