### ISSUE TITLE
[ENHANCEMENT] Sexual intercourse

### ISSUE THREAD

**Issue by Mitality** [aematsubara/RealisticVillagers#41]
So, a friend of mine and I were messing around in mc when he jokingly suggested to add this to RV and at first glance it doesn't seem possible, but upon investigation, we discovered a way to achieve shockingly realistic positions for procreation...

When a player model is in crawling position, it's hitbox is cut in half vertically, but it isn't modified horizontally or rotated in any way. Since the playermodel alway stays at the center of the corresponding hitbox, this leads to the playermodel floating above the ground just enough to fit another model below it.

When a player/NPC is lying in bed, this doesn't happen, because someone at mojang thought of this and ensured that a playermodel touches the bed visually when sleeping.

So, we now have a way to force players/NPCs into a position where they are lying face up, visually touching the ground/bed and a second position face down just on top of the first model. Minecraft even raises the head of the player on top just a bit, which prevents it from glitching into the head of the player in bed and makes it seem even more realistic.

Here's how to achieve this with a plugin:
- Place the NPC a player is married to in a bed, sleeping.
- Place the player 1 block above the beds center and simmulate barrier blocks 2 blocks above the bed (If you don't now how to do that, just borrow that code from the open source plugin "GSit" or place actual barriers temporarily)
- Prevent the player on top from moving forward or sideways during procreation (maybe move the player briefly to simmulate movement if you wanna go crazy with this)
- Prevent the placer from exceeding certain limits when looking around, because the playermodel starts rotating whenn looking too much left or right
- Have heart particles appear around the top half of the bed / around the two player heads

If you need some more information, let me know!

...and here is some footage:
![Screenshot_2024-06-18_124547](https://github.com/aematsubara/RealisticVillagers/assets/96748385/1186327e-bb1a-409d-b50b-47f09a2eab65)
![Screenshot_2024-06-18_124527](https://github.com/aematsubara/RealisticVillagers/assets/96748385/159912db-a5f3-405e-99da-1900507f876b)
![Screenshot_2024-06-18_124749](https://github.com/aematsubara/RealisticVillagers/assets/96748385/299c684e-0a80-400b-8f65-3be6b0d28228)

**Comment by Mitality** [comment]
(If you're crazy enough to add this, you probably want to make this an optional feature)

**Comment by dudubles** [comment]
Jajajaja ni cagando

**Comment by Mitality** [comment]
Simplemente tuvimos que sugerirlo xD

**Comment by aematsubara** [comment]
🤣🤣🤣🤣

I can't do this. The plugin would be removed from spigot after 0.000001 seconds. Thanks for the suggestion anyway!

**Comment by mfnalex** [comment]
I second this

**Comment by Mitality** [comment]
Did I hear unofficial addon? 😅
