### ISSUE TITLE
Can´t rejoin Server - Error

### ISSUE THREAD

**Issue by chillgerne89** [aematsubara/RealisticVillagers#42]
A player on my server was just fighting against Pillagers at a Pillager Outpost when he was suddenly kicked from the server. When he tried to rejoin the server, he received the following error message while loading the world:

InternalException: io.netty.handler.codec.EncoderException:
java.lang.NullPointerException: Cannot invoke
“com.github.retrooper.packetevents.protocol.mapper.MappedEntity.isRegistred()”
because “entity” is null

The server console shows that the player is joining the server, and then the following error message appears: 
[Server thread/INFO]: PlayerXYZ lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.mapper.MappedEntity.isRegistered()" because "entity" is null

All other players can continue to play without any problems. I updated the server to the latest Paper 1.20.6 version and ran a region fixer. I also completely reinstalled the Minecraft client for the player. Only after I deleted the RealisticVillager plugin from the server, the player was able to join the server again.
I hope you can find out what the problem is so that I can use the plugin again.

I uploaded a Logfile with the Error here (time of the Error 16:43:00):
[2024-06-26-2.log](https://github.com/user-attachments/files/16007881/2024-06-26-2.log)

**Comment by aematsubara** [comment]
Hi! Please, try with the latest release of RealisticVillagers and the latest release of PacketEvents (2.4.0). If this change doesn't fix the issue, try using a dev-build of PacketEvents from here: https://ci.codemc.io/job/retrooper/job/packetevents/

**Comment by chillgerne89** [comment]
I have updated both plugins to the latest release. Currently, everything is running without any problems. I hope it stays that way. Thank you.

**Comment by aematsubara** [comment]
> I have updated both plugins to the latest release. Currently, everything is running without any problems. I hope it stays that way. Thank you.

Good to know! I'll close this issue, feel free to re-open this if the issue persist!
