### ISSUE TITLE
PacketEvent Issue

### ISSUE THREAD

**Issue by EchocallingEarth** [aematsubara/RealisticVillagers#44]
Realistic Villagers Packet Event Warning flooding console - [https://pastebin.com/CHj439R6](url)

**Comment by aematsubara** [comment]
For some reason I can't open the link you sent but I guess it's the same issue other people are having, try updating this plugin to the latest release and use the latest dev-build from PacketEvents

**Comment by aematsubara** [comment]
I'll close this, let me know if it happens again
