### ISSUE TITLE
spigot-1.21 is not useful

### ISSUE THREAD

**Issue by chen17-yixuan** [aematsubara/RealisticVillagers#46]
console message
![image](https://github.com/user-attachments/assets/75cd93be-1d47-4f27-a4f7-f556e181d5cd)

![image](https://github.com/user-attachments/assets/e71b2e23-a467-497e-b11d-491f3a3eb9ea)

**Comment by aematsubara** [comment]
Hi, try with the latest release (3.3.3.1)

**Comment by aematsubara** [comment]
Ok, I found a solution to this issue, sorry for the inconvenience! I'll update it soon
