### ISSUE TITLE
Compatibility Issue with RealisticVillagers plugin and Paper 1.21.1 - Reflection and ClassCastException Errors

### ISSUE THREAD

**Issue by thisisaef** [aematsubara/RealisticVillagers#47]
**Describe the bug**
The RealisticVillagers plugin is failing to initialize properly on Paper 1.21.1 due to reflection issues and class casting exceptions when trying to handle GameProfile and skin loading.

**Expected Behavior**
The plugin should enable successfully, load skins, and function without reflection or class casting errors. Player heads and custom items should be created properly without errors in the console.

**Actual Behavior**
When enabling the plugin, multiple warnings are logged related to reflection (`NoSuchMethodException`) and class casting (`ClassCastException`). Specifically, the plugin is unable to invoke `setProfile` on `CraftMetaSkull `and fails to cast `GameProfile` to `ResolvableProfile`. As a result, custom items and skins are not handled correctly.

**Steps to Reproduce**
1. Install the RealisticVillagers plugin version 3.3.3.3 on a Paper 1.21.1 server.
2. Start the server.
3. Observe the console logs during startup for warnings related to `NoSuchMethodException` and `ClassCastException`.

**Log**
latest.log: https://paste.helpch.at/ocoyeqarox.makefile

**Plugin List**
• RealisticVillagers v3.3.3.3
• packetevents-spigot-2.5.0-SNAPSHOT-b563

**Software brand**
• Backend: Paper 1.21.1-77-4ff58c4 (MC: 1.21.1)

**Additional Information**
The errors seem to stem from the plugin trying to access methods or classes that have changed in newer versions of Paper or Minecraft. Specifically, reflection errors occur while handling player skins and creating custom items, likely due to changes in how `GameProfile` and `CraftMetaSkull` are managed. This issue may require updating the plugin to support the latest Minecraft/Paper API.

**Comment by aematsubara** [comment]
Hi, thanks for reporting! A fix is being made, this seems to be an issue with a lot of plugins with newer versions of paper
