### ISSUE TITLE
"Invalid textures!" exception

### ISSUE THREAD

**Issue by marcelschoen** [aematsubara/RealisticVillagers#6]
I am using version 1.2.1 of the plugin, on PaperMC 1.19.2. I noticed that while in general the plugin seems to work, I sometimes get these exceptions in the console log:

```
deadlyrealms    | [22:06:19 ERROR]: Could not pass event EntitiesLoadEvent to RealisticVillagers v1.2.1
deadlyrealms    | java.lang.IllegalArgumentException: Invalid textures!
deadlyrealms    | 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
deadlyrealms    | 	at me.matsubara.realisticvillagers.tracker.VillagerTracker.spawnNPC(VillagerTracker.java:458) ~[RealisticVillagers-1.2.1.jar:?]
deadlyrealms    | 	at me.matsubara.realisticvillagers.tracker.VillagerTracker.handleSpawn(VillagerTracker.java:374) ~[RealisticVillagers-1.2.1.jar:?]
deadlyrealms    | 	at me.matsubara.realisticvillagers.tracker.VillagerTracker.handleSpawn(VillagerTracker.java:358) ~[RealisticVillagers-1.2.1.jar:?]
deadlyrealms    | 	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
deadlyrealms    | 	at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:?]
deadlyrealms    | 	at me.matsubara.realisticvillagers.tracker.VillagerTracker.onEntitiesLoad(VillagerTracker.java:316) ~[RealisticVillagers-1.2.1.jar:?]
deadlyrealms    | 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor32.execute(Unknown Source) ~[?:?]
deadlyrealms    | 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
deadlyrealms    | 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-177]
deadlyrealms    | 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
deadlyrealms    | 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
deadlyrealms    | 	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactory.java:1902) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.world.ChunkEntitySlices.callEntitiesLoadEvent(ChunkEntitySlices.java:151) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:914) ~[?:?]
deadlyrealms    | 	at net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:851) ~[?:?]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1310) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1036) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1020) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:905) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.scheduleTickingState(ChunkTaskScheduler.java:293) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.scheduleChunkLoad(ChunkTaskScheduler.java:399) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:533) ~[?:?]
deadlyrealms    | 	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:440) ~[?:?]
deadlyrealms    | 	at net.minecraft.world.level.Level.getChunk(Level.java:502) ~[?:?]
deadlyrealms    | 	at net.minecraft.world.level.Level.getChunk(Level.java:442) ~[?:?]
deadlyrealms    | 	at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getHighestBlockYAt(CraftWorld.java:983) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getHighestBlockAt(CraftWorld.java:993) ~[paper-1.19.2.jar:git-Paper-177]

```

**Comment by marcelschoen** [comment]
Maybe an issue with downloading the skins from somewhere else?

**Comment by aematsubara** [comment]
This is something related to paper loading entities, I think I got a fix to this. Any steps on how to reproduce this error? So I can test if it's fixed. I'm sure my solution should fix this tho

**Comment by marcelschoen** [comment]
I can't say I can reproduce it specifically, but I keep seeing it quite a lot on my test server. I see the exact same error with the plugin "CustomStructures" when I defined invalid HTTP urls for custom NPC skins. Not sure what causes it with your plugin; maybe SOME of the skins are actually invalid / do not exist?

**Comment by marcelschoen** [comment]
I will gladly test a snapshot build from you, to check if the problem disappears.

**Comment by aematsubara** [comment]
> I can't say I can reproduce it specifically, but I keep seeing it quite a lot on my test server. I see the exact same error with the plugin "CustomStructures" when I defined invalid HTTP urls for custom NPC skins. Not sure what causes it with your plugin; maybe SOME of the skins are actually invalid / do not exist?

All skins were generated using mineskins so that shouldn't be the problem; all add more debug messages to try to find the reason



> I will gladly test a snapshot build from you, to check if the problem disappears.

Sure! do you have a discord where I can send you the jar?

**Comment by marcelschoen** [comment]
No, I did change absolutely nothing. Basically just dropped the plugin in without customizing anything at all. I don't really have / use Discord, but you can just mail it to me if that's OK:

marcelschoen@yahoo.com

**Comment by marcelschoen** [comment]
Or I can build it myself, I guess, if you push the branch with the fix in it.

**Comment by aematsubara** [comment]
Since I don't know if the fix is working I can't do the commit yet, so I just sent it to your email!

**Comment by aematsubara** [comment]
ok, now I think I've found the solution.

**Comment by aematsubara** [comment]
Should be fixed now, I'll let this open if still happening, but based on my testings, it's working good

**Comment by marcelschoen** [comment]
OK, great. Should I test it? Do you have another snapshot build? I don't see a new branch in the GIT repo. Are your fixes in the master branch?

**Comment by marcelschoen** [comment]
By the way, I just tried to build it myself (master branch), but the maven build failed due to a missing dependency:

[ERROR] Failed to execute goal on project realisticvillagers-1_18_R2: Could not resolve dependencies for project me.matsubara:realisticvillagers-1_18_R2:jar:1.2.2: Failure to find org.spigotmc:spigot:jar:remapped-mojang:1.18.2-R0.1-SNAPSHOT in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigotmc-repo has elapsed or updates are forced -> [Help 1]

**Comment by marcelschoen** [comment]
Ah I see, there is a new release. I will test it immediately.

**Comment by marcelschoen** [comment]
Actually, your latest release now interferes with the CustomStructures plugin in that when the CustomStructures plugin wants to spawn an NPC (Citizen NPC) of type "VILLAGER", it spawns one of your villagers. Hm... but that could actually be a cool feature, not a problem. Have to test it out a little.

**Comment by marcelschoen** [comment]
You know what? This is actually great!!! With the "CustomStructures" plugin, I was using VILLAGER-Types NPCs in some cases, and PLAYER-type NPCs in others. I used the PLAYER-types one to get, well, player-type skins. But now I can juse define all of them as VILLAGER-type, and then they still all look like players, thanks to your plugin.

This works great for me! As far as I'm concerned, you can consider this issue close! Thanks for the quick reaction!!!

**Comment by aematsubara** [comment]
> By the way, I just tried to build it myself (master branch), but the maven build failed due to a missing dependency:
> 
> [ERROR] Failed to execute goal on project realisticvillagers-1_18_R2: Could not resolve dependencies for project me.matsubara:realisticvillagers-1_18_R2:jar:1.2.2: Failure to find org.spigotmc:spigot:jar:remapped-mojang:1.18.2-R0.1-SNAPSHOT in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigotmc-repo has elapsed or updates are forced -> [Help 1]

That's because to use NMS you must use BuildTools to generate the sources.
You can also use this repository to get them, tho it's always recommended to just run BuildTools.
`<repository>
    <id>nms-repo</id>
    <url>https://repo.codemc.io/repository/nms/</url>
</repository>`



> You know what? This is actually great!!! With the "CustomStructures" plugin, I was using VILLAGER-Types NPCs in some cases, and PLAYER-type NPCs in others. I used the PLAYER-types one to get, well, player-type skins. But now I can just define all of them as VILLAGER-type, and then they still all look like players, thanks to your plugin.
> 
> This works great for me! As far as I'm concerned, you can consider this issue closed! Thanks for the quick reaction!!!

Well, that's cool then!
