### ISSUE TITLE
DecoderException string buffer lenght

### ISSUE THREAD

**Issue by JustYsuf** [aematsubara/RealisticVillagers#8]
![image](https://user-images.githubusercontent.com/69390801/193465034-ca1c7ee1-2788-4c45-9013-e73b0af57ebb.png)

This error only appears when the plugin is running.
What could be the causes of this error?

**Comment by aematsubara** [comment]
Hi! Which server software are you using? there should be an error in console

**Comment by JustYsuf** [comment]
If you mean my server core, i use Mirai and when i am getting kicked from server, there is no error in console, i am just getting kicked.

**Comment by JustYsuf** [comment]
> If you mean my server core, i use Mirai and when i am getting kicked from server, there is no error in console, i am just getting kicked.



> Hi! Which server software are you using? there should be an error in console

If you mean my server core, i use Mirai and when i am getting kicked from server, there is no error in console, i am just getting kicked.

**Comment by aematsubara** [comment]
I see... then I would need to see your latest client log to see if there's any stacktrace. Wouldn't be a surprise that this software is the reason of this issue.

**Comment by JustYsuf** [comment]
> I see... then I would need to see your latest client log to see if there's any stacktrace (when you get kicked). Wouldn't be a surprise that this software is the reason of this issue.

[latest.log](https://github.com/aematsubara/RealisticVillagers/files/9696757/latest.log)
Client logs

https://logs.hosting-minecraft.pro/fiyaduzige
Server logs

**Comment by aematsubara** [comment]
Well, this is very unusual. There's nothing wrong in the logs so I don't even know where should I start. My only guess right now might be that something's wrong in Mirai code but can't be sure; are you using the lastest dev version of ProtocolLib?

**Comment by JustYsuf** [comment]
> Well, this is very unusual. There's nothing wrong in the logs so I don't even know where should I start. My only guess right now might be that something's wrong in Mirai code but can't be sure; are you using the lastest dev version of ProtocolLib?

I found bug, when i change names of villagers in names.yml to cyrrilic names and when i spawn villager with cyrrilic name like "Макс" i'm getting kicked

**Comment by aematsubara** [comment]
Bingo. That's the reason. Player names only accepts a-zA-Z0-9_(16) https://help.minecraft.net/hc/en-us/articles/4408950195341-Minecraft-Java-Edition-Username-VS-Gamertag-FAQ#h_01GE5JWW0210X02JZN2FP9CREC

So for now, I recommend you to disable nametags. In a future, I'll add a different nametag system where every character will be allowed, multiline, no characters length limit, etc.

**Comment by JustYsuf** [comment]
> Bingo. That's the reason. Player names only accepts a-zA-Z0-9_(16) https://help.minecraft.net/hc/en-us/articles/4408950195341-Minecraft-Java-Edition-Username-VS-Gamertag-FAQ#h_01GE5JWW0210X02JZN2FP9CREC
> 
> So for now, I recommend you to disable nametags. In a future, I'll add a different nametag system where every character will be allowed, multiline, no characters length limit, etc.

Ok, thank you for support
