### ISSUE TITLE
Suicidal armed villagers

### ISSUE THREAD

**Issue by mschoenUsp** [aematsubara/RealisticVillagers#9]
Hi there,

I just noticed that the armed villagers can be a bit suicidal. Villagers with swords will try to attack zombies, but as soon as they get to the zombie, they are instantly infected and turned into zombie villagers. This basically makes them suicidal. They don't seem to have a chance to land even one hit on a zombie before being infected and turned. I don't know how much their behavior can be adjusted, so I'll just give some thoughts on how it could be addressed:

- Let villagers with melee weapons attack only creepers, skeletons or pillagers - but not zombies. Make them run away when they see a zombie.
- Villagers with bows attack zombies if they are still a certain minimum distance away (like at least 15 blocks or so), but run away when the zombie gets closer.

Alternatively, allow to completely disable armed villagers altogether, so they will just behave as in vanilla minecraft and just run and hide.

Additionally, all the villagers weapons should have the "knockback" (sword) or "punch" (bow) enchantment.

**Comment by aematsubara** [comment]
I'll try to implement the same back-up system when using bow/crossbow to the melee attack too, shouldn't be that hard!

**Comment by aematsubara** [comment]
Check the latest release for the new melee attack range option! If you see them getting attack, go increasing the range up to 4 (not higher or it'll look a bit unreal IMO).

**Comment by marcelschoen** [comment]
The latest release works amazingly well! Surprisingly, the villagers don't get infected apparently, even when they run straight into the zombies... but also, they now attack the zombies quite effectively! Well done, and thanks!!

**Comment by marcelschoen** [comment]
I can't close this issue myself, so you may close it as far as I'm concerned.

**Comment by aematsubara** [comment]
Nice!
